### ISSUE TITLE
OS X OpenSSL issues

### ISSUE THREAD

**Issue by kkirby** [stephan-nordnes-eriksen/ruby_ship#5]
Hello.

When I try to run `gem install`, I get this issue:

    ERROR:  Loading command: install (LoadError)
    	dlopen(/Users/kkirby/.gs-project/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.1.0/x86_64-darwin13.0/openssl.bundle, 9): Symbol not found: _SSLv2_client_method
      Referenced from: /Users/kkirby/.gs-project/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.1.0/x86_64-darwin13.0/openssl.bundle
      Expected in: ../bin/shipyard/darwin_ruby/ruby_ship_dylibs/libssl.1.0.0.dylib
     in /Users/kkirby/.gs-project/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.1.0/x86_64-darwin13.0/openssl.bundle - /Users/kkirby/.gs-project/ruby_ship/bin/shipyard/darwin_ruby/lib/ruby/2.1.0/x86_64-darwin13.0/openssl.bundle
    ERROR:  While executing gem ... (NoMethodError)
        undefined method `invoke_with_build_args' for nil:NilClass

I have an older version of ruby_ship and it works just fine, but this new version is broken for me.

I did run the `auto_relink_dylibs.rb` script, but it didn't help.

**Comment by stephan-nordnes-eriksen** [comment]
@kkirby I have now pushed a new version for osx. I have also tweaked the dylib-relinker. Because of the way the dylibs works, the new distro is quite a bit larger (roughly 330MB more :s ), but it is the only way to achieve true portability on osx I am afraid.

Anyways, the new version should be lots more stable. And I would advice upgrading to that ;)

Also note: If you are going to install new gems, you must do so from a platform which has all dev-dependencies installed (c-compiler and all that). If you install a gem which somehow uses dylibs, you should re-run the `ruby tools/auto_relink_dylibs.rb`.

**Comment by kkirby** [comment]
Awesome, thanks!

**Comment by stephan-nordnes-eriksen** [comment]
I would just like to note that the more I dig into this issue, the more apparent it becomes to me that this does not work as expected. I am working on a fix now, but no guarantees.

**Comment by stephan-nordnes-eriksen** [comment]
@kkirby I have pushed a fix now. Can you maybe test it by downloading the newest and run the command:

`bin/ruby_ship.sh tools/implementation_tests.rb`

If everything works it should say something like "All tests passed. Ruby ship ready to sail".

It would be a great help because this stuff is quite hard to test on my own machine.

**Comment by kkirby** [comment]
Yeah, I'll test it out later today or on Monday. thanks!

**Comment by stephan-nordnes-eriksen** [comment]
Thanks a lot :) Really hope I solved the issue now.

**Comment by stephan-nordnes-eriksen** [comment]
I have got multiple people to test this out now. It appears to work on all machines testes thus far. I feel confident enough that I am closing the issue. None the less, I would like you to actually test it out as well. This fix should fix both the openssl issue and the dylib trouble I have been seeing.
